replicaCount: 2

image:
  repository: sse-test
  tag: v1.0.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

container:
  env:
    SPRING_APPLICATION_NAME: SSE-Test
    SERVER_PORT: 8080
    SERVER_SERVLET_CONTEXT_PATH: /sse

autoscaling:
  enabled: false

serviceAccount:
  create: false


ingress:
  enabled: true
  ingressClassName: traefik  # Use Traefik as the Ingress controller
  annotations:
    kubernetes.io/ingress.class: "traefik"  # Traefik-specific annotation
    traefik.ingress.kubernetes.io/router.entrypoints: "web"  # Optional: Specify Traefik entrypoint
  hosts:
    - host: minikube.local
      paths:
        - path: /sse
          pathType: Prefix
  tls: []